"""Self-legislation cycle — Elected leaders propose, members vote, rules auto-activate.

End-to-end flow:
1. An elected leader identifies a governance issue via metrics analysis.
2. The leader creates a structured rule proposal (via RuleProposalEngine).
3. Organization members vote on the proposal.
4. When quorum + majority threshold is met, the rule auto-activates in
   the RuleEngine and is enforced from the next tick.

This module provides the orchestration layer that connects the existing
governance analysis, rule proposal, and rule engine components.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Protocol

from .governance_analysis import (
    GovernanceAnalyzer,
    GovernanceEventData,
    OrgGovernanceSnapshot,
    StabilityReport,
)
from .rule_proposal import (
    RuleCategory,
    RuleCondition,
    RuleEffect,
    RuleProposal,
    RuleProposalEngine,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class LegislationStatus(str, Enum):
    """Status of a legislation cycle."""

    IDLE = "idle"
    ANALYZING = "analyzing"
    PROPOSING = "proposing"
    CAMPAIGNING = "campaigning"
    VOTING = "voting"
    ENACTED = "enacted"
    REJECTED = "rejected"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Default quorum: minimum number of votes required for auto-activation.
DEFAULT_QUORUM: int = 3

# Default majority ratio: votes_for / (votes_for + votes_against) must exceed this.
DEFAULT_MAJORITY_RATIO: float = 0.5


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LegislationCycle:
    """Record of a single legislation cycle (election → proposal → vote → enactment).

    Attributes:
        cycle_id: Unique identifier for this legislation cycle.
        org_id: Organization that this legislation applies to.
        leader_id: The elected leader who initiated the cycle.
        proposal: The rule proposal generated by the leader.
        status: Current status of the cycle.
        votes_for: Number of votes in favor.
        votes_against: Number of votes against.
        voters: Set of agent IDs who have voted.
        stability_report: Governance stability analysis that triggered this cycle.
        trigger_reason: Human-readable reason for the legislation.
        enacted_rule_id: ID of the rule in the rule engine (set after enactment).
    """

    cycle_id: str
    org_id: str
    leader_id: str
    proposal: RuleProposal | None = None
    status: LegislationStatus = LegislationStatus.IDLE
    votes_for: int = 0
    votes_against: int = 0
    voters: frozenset[str] = field(default_factory=frozenset)
    stability_report: StabilityReport | None = None
    trigger_reason: str = ""
    enacted_rule_id: str | None = None


# ---------------------------------------------------------------------------
# Protocol for rule engine client
# ---------------------------------------------------------------------------


class RuleEngineClient(Protocol):
    """Interface for submitting rules and votes to the world engine.

    In production, this wraps HTTP calls to the Rust API.
    In tests, it can be a mock.
    """

    def submit_rule(
        self,
        proposer_id: str,
        org_id: str,
        title: str,
        description: str,
        rule_type: str,
        conditions: list[dict[str, Any]],
        effects: list[dict[str, Any]],
        created_tick: int,
        expires_tick: int | None = None,
    ) -> str:
        """Submit a rule proposal. Returns the rule ID."""
        ...

    def cast_vote(self, rule_id: str, voter_id: str, support: bool) -> None:
        """Cast a vote on a rule proposal."""
        ...

    def try_auto_activate(self, rule_id: str, quorum: int) -> bool:
        """Check if a rule meets activation threshold and activate it."""
        ...


# ---------------------------------------------------------------------------
# Self-Legislation Cycle Engine
# ---------------------------------------------------------------------------


class SelfLegislationCycleEngine:
    """Orchestrates the self-legislation cycle for an organization.

    The cycle connects governance analytics to the rule engine:
    1. **Analyze**: Use GovernanceAnalyzer to assess org stability.
    2. **Evaluate**: Check if the elected leader should propose a rule.
    3. **Propose**: Generate a structured rule proposal.
    4. **Campaign**: Generate campaign messaging for members.
    5. **Vote**: Collect votes from organization members.
    6. **Enact**: Auto-activate the rule when quorum + majority is met.

    Usage::

        engine = SelfLegislationCycleEngine()
        cycle = engine.start_cycle(
            leader_id="agent-1",
            org_id="org-123",
            org_snapshot=org_snapshot,
            events=governance_events,
            context=governance_context,
        )
        # ... members vote ...
        result = engine.finalize_cycle(cycle, rule_engine_client)
    """

    def __init__(
        self,
        *,
        quorum: int = DEFAULT_QUORUM,
        majority_ratio: float = DEFAULT_MAJORITY_RATIO,
        proposal_engine: RuleProposalEngine | None = None,
        analyzer: GovernanceAnalyzer | None = None,
    ) -> None:
        self._quorum = quorum
        self._majority_ratio = majority_ratio
        self._proposal_engine = proposal_engine or RuleProposalEngine()
        self._analyzer = analyzer or GovernanceAnalyzer()

    # ── Start Cycle ────────────────────────────────────────

    def start_cycle(
        self,
        leader_id: str,
        org_id: str,
        org_snapshot: OrgGovernanceSnapshot,
        events: list[GovernanceEventData],
        context: dict[str, Any],
        *,
        cycle_id: str | None = None,
    ) -> LegislationCycle | None:
        """Attempt to start a self-legislation cycle.

        The leader evaluates governance conditions and, if warranted,
        creates a rule proposal. Returns None if no legislation is needed.

        Args:
            leader_id: ID of the elected leader proposing legislation.
            org_id: Organization ID.
            org_snapshot: Current governance snapshot of the org.
            events: Historical governance events for analysis.
            context: Additional context (members, resources, etc.).
            cycle_id: Optional explicit cycle ID (auto-generated if None).

        Returns:
            A LegislationCycle with PROPOSING status, or None if no
            legislation is needed.
        """
        import uuid

        # Step 1: Analyze governance stability
        stability = self._analyzer.analyze_org_stability(org_snapshot, events)

        # Step 2: Check if a rule should be proposed
        should_propose, reason = self._proposal_engine.should_propose_rule(
            leader_id, org_id, context,
        )

        if not should_propose:
            logger.debug(
                "No legislation needed for org %s: %s", org_id, reason
            )
            return None

        # Step 3: Generate the rule proposal
        proposal = self._proposal_engine.generate_rule_proposal(
            leader_id, org_id, reason, context,
        )

        # Step 4: Build the campaign message
        campaign = self._proposal_engine.campaign_for_rule(leader_id, proposal)

        cid = cycle_id or str(uuid.uuid4())
        cycle = LegislationCycle(
            cycle_id=cid,
            org_id=org_id,
            leader_id=leader_id,
            proposal=proposal,
            status=LegislationStatus.CAMPAIGNING,
            stability_report=stability,
            trigger_reason=reason,
        )

        logger.info(
            "Legislation cycle %s started: %s (reason: %s)",
            cid, proposal.title, reason,
        )
        # Store campaign message for external use
        self._last_campaign = campaign
        return cycle

    # ── Voting ─────────────────────────────────────────────

    def cast_vote(
        self,
        cycle: LegislationCycle,
        voter_id: str,
        support: bool,
    ) -> LegislationCycle:
        """Cast a vote on a legislation cycle.

        Returns a new LegislationCycle with updated vote counts.
        Ignores duplicate votes (same voter_id).
        """
        if voter_id in cycle.voters:
            logger.warning(
                "Duplicate vote from %s on cycle %s", voter_id, cycle.cycle_id
            )
            return cycle

        new_voters = cycle.voters | {voter_id}
        new_for = cycle.votes_for + (1 if support else 0)
        new_against = cycle.votes_against + (1 if not support else 0)

        return LegislationCycle(
            cycle_id=cycle.cycle_id,
            org_id=cycle.org_id,
            leader_id=cycle.leader_id,
            proposal=cycle.proposal,
            status=LegislationStatus.VOTING,
            votes_for=new_for,
            votes_against=new_against,
            voters=frozenset(new_voters),
            stability_report=cycle.stability_report,
            trigger_reason=cycle.trigger_reason,
            enacted_rule_id=cycle.enacted_rule_id,
        )

    # ── Finalization ───────────────────────────────────────

    def finalize_cycle(
        self,
        cycle: LegislationCycle,
        client: RuleEngineClient,
    ) -> LegislationCycle:
        """Finalize a legislation cycle by submitting and activating the rule.

        If the cycle has a proposal and meets quorum + majority, the rule
        is submitted to the rule engine and auto-activated.

        Returns the updated LegislationCycle with ENACTED or REJECTED status.
        """
        if cycle.proposal is None:
            return LegislationCycle(
                cycle_id=cycle.cycle_id,
                org_id=cycle.org_id,
                leader_id=cycle.leader_id,
                status=LegislationStatus.FAILED,
                trigger_reason=cycle.trigger_reason or "no proposal",
            )

        # Submit the rule to the engine
        proposal = cycle.proposal
        conditions_dicts = [
            {"field": c.field, "operator": c.operator, "value": c.value}
            for c in proposal.conditions
        ]
        effects_dicts = [
            {"target": e.target, "action": e.action, "value": e.value}
            for e in proposal.effects
        ]

        try:
            rule_id = client.submit_rule(
                proposer_id=proposal.proposer_id,
                org_id=proposal.org_id,
                title=proposal.title,
                description=proposal.description,
                rule_type=proposal.rule_type.value,
                conditions=conditions_dicts,
                effects=effects_dicts,
                created_tick=0,
                expires_tick=proposal.expires_ticks,
            )
        except Exception as exc:
            logger.error("Failed to submit rule: %s", exc)
            return LegislationCycle(
                cycle_id=cycle.cycle_id,
                org_id=cycle.org_id,
                leader_id=cycle.leader_id,
                proposal=cycle.proposal,
                status=LegislationStatus.FAILED,
                trigger_reason=f"submit failed: {exc}",
            )

        # Cast the collected votes
        for voter_id in cycle.voters:
            support = _voter_supported(cycle, voter_id)
            try:
                client.cast_vote(rule_id, voter_id, support)
            except Exception as exc:
                logger.warning("Vote failed for %s: %s", voter_id, exc)

        # Try auto-activation
        activated = client.try_auto_activate(rule_id, self._quorum)

        if activated:
            logger.info("Rule %s enacted for org %s", rule_id, cycle.org_id)
            return LegislationCycle(
                cycle_id=cycle.cycle_id,
                org_id=cycle.org_id,
                leader_id=cycle.leader_id,
                proposal=cycle.proposal,
                status=LegislationStatus.ENACTED,
                votes_for=cycle.votes_for,
                votes_against=cycle.votes_against,
                voters=cycle.voters,
                stability_report=cycle.stability_report,
                trigger_reason=cycle.trigger_reason,
                enacted_rule_id=rule_id,
            )

        return LegislationCycle(
            cycle_id=cycle.cycle_id,
            org_id=cycle.org_id,
            leader_id=cycle.leader_id,
            proposal=cycle.proposal,
            status=LegislationStatus.REJECTED,
            votes_for=cycle.votes_for,
            votes_against=cycle.votes_against,
            voters=cycle.voters,
            stability_report=cycle.stability_report,
            trigger_reason=cycle.trigger_reason,
        )

    # ── Batch Cycle ────────────────────────────────────────

    def run_full_cycle(
        self,
        leader_id: str,
        org_id: str,
        org_snapshot: OrgGovernanceSnapshot,
        events: list[GovernanceEventData],
        context: dict[str, Any],
        member_votes: dict[str, bool],
        client: RuleEngineClient,
    ) -> LegislationCycle | None:
        """Run the complete legislation cycle in one call.

        Convenience method that combines start_cycle, cast_vote, and
        finalize_cycle for all members.

        Args:
            leader_id: Elected leader who proposes.
            org_id: Organization ID.
            org_snapshot: Current governance snapshot.
            events: Historical governance events.
            context: Additional context for proposal generation.
            member_votes: Mapping of member_id → support (True/False).
            client: Rule engine client for submitting and activating.

        Returns:
            The final LegislationCycle, or None if no legislation was needed.
        """
        cycle = self.start_cycle(
            leader_id, org_id, org_snapshot, events, context,
        )
        if cycle is None:
            return None

        for member_id, support in member_votes.items():
            cycle = self.cast_vote(cycle, member_id, support)

        return self.finalize_cycle(cycle, client)

    @property
    def last_campaign_message(self) -> str:
        """Get the campaign message from the most recent cycle."""
        return getattr(self, "_last_campaign", "")

    @property
    def quorum(self) -> int:
        return self._quorum

    @property
    def majority_ratio(self) -> float:
        return self._majority_ratio


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _voter_supported(cycle: LegislationCycle, voter_id: str) -> bool:
    """Determine whether a voter voted in favor.

    Uses the vote counts to reconstruct: if votes_for > 0 and the voter
    is in the first votes_for positions of the voters set, they supported.
    This is a simplification for the batch API.
    """
    # In practice, we track this per-voter in the cycle voters frozenset.
    # Since frozenset is unordered, we use a deterministic approach:
    # first `votes_for` sorted voter IDs are considered "for".
    sorted_voters = sorted(cycle.voters)
    for_voters = sorted_voters[: cycle.votes_for]
    return voter_id in for_voters


# ---------------------------------------------------------------------------
# In-memory RuleEngineClient for testing
# ---------------------------------------------------------------------------


class InMemoryRuleEngineClient:
    """Simple in-memory client for testing the legislation cycle.

    Simulates the Rust rule engine API without network calls.
    """

    def __init__(self) -> None:
        self._rules: dict[str, dict[str, Any]] = {}
        self._votes: dict[str, dict[str, bool]] = {}
        self._next_id = 0

    def submit_rule(
        self,
        proposer_id: str,
        org_id: str,
        title: str,
        description: str,
        rule_type: str,
        conditions: list[dict[str, Any]],
        effects: list[dict[str, Any]],
        created_tick: int,
        expires_tick: int | None = None,
    ) -> str:
        self._next_id += 1
        rule_id = f"rule-{self._next_id}"
        self._rules[rule_id] = {
            "proposer_id": proposer_id,
            "org_id": org_id,
            "title": title,
            "description": description,
            "rule_type": rule_type,
            "conditions": conditions,
            "effects": effects,
            "status": "proposed",
        }
        self._votes[rule_id] = {}
        return rule_id

    def cast_vote(self, rule_id: str, voter_id: str, support: bool) -> None:
        if rule_id not in self._votes:
            raise ValueError(f"Rule {rule_id} not found")
        self._votes[rule_id][voter_id] = support

    def try_auto_activate(self, rule_id: str, quorum: int) -> bool:
        if rule_id not in self._rules:
            return False
        votes = self._votes.get(rule_id, {})
        if len(votes) < quorum:
            return False
        for_count = sum(1 for v in votes.values() if v)
        against_count = len(votes) - for_count
        if for_count > against_count:
            self._rules[rule_id]["status"] = "active"
            return True
        return False
