//! Subsystem trait — pluggable components executed each tick.
//!
//! Each Subsystem receives the current tick and a mutable reference to
//! the agent roster, returning any [`WorldEvent`]s it generates.
//! Subsystems are registered in a [`SubsystemRegistry`] and run in
//! insertion order during every tick.

use uuid::Uuid;

use crate::economy::token_burn::AgentRecord;
use crate::world::event::WorldEvent;

/// A pluggable subsystem that participates in the tick loop.
///
/// Implementations handle one phase of the tick pipeline:
/// token consumption, death judgment, rule evaluation, event broadcast, etc.
pub trait Subsystem: Send + Sync {
    /// Human-readable name for logging / diagnostics.
    fn name(&self) -> &str;

    /// Execute this subsystem for the given tick.
    ///
    /// `agents` is a slice of `(agent_id, spawn_tick, record)` tuples that
    /// the subsystem may mutate in place (e.g. deduct tokens, change phase).
    ///
    /// Returns a list of events generated by this subsystem.
    fn on_tick(
        &self,
        tick: u64,
        agents: &mut [(Uuid, u64, AgentRecord)],
    ) -> Vec<WorldEvent>;
}

// ═══════════════════════════════════════════════════════════════════════════
// Subsystem Registry
// ═══════════════════════════════════════════════════════════════════════════

/// Ordered collection of subsystems executed each tick.
pub struct SubsystemRegistry {
    subsystems: Vec<Box<dyn Subsystem>>,
}

impl SubsystemRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self {
            subsystems: Vec::new(),
        }
    }

    /// Append a subsystem. Subsystems run in the order they are registered.
    pub fn register(&mut self, subsystem: Box<dyn Subsystem>) {
        self.subsystems.push(subsystem);
    }

    /// Number of registered subsystems.
    pub fn len(&self) -> usize {
        self.subsystems.len()
    }

    /// Whether the registry is empty.
    pub fn is_empty(&self) -> bool {
        self.subsystems.is_empty()
    }

    /// Execute all subsystems for a single tick, returning all generated events.
    pub fn run_tick(
        &self,
        tick: u64,
        agents: &mut [(Uuid, u64, AgentRecord)],
    ) -> Vec<WorldEvent> {
        let mut events = Vec::new();
        for subsystem in &self.subsystems {
            let mut produced = subsystem.on_tick(tick, agents);
            events.append(&mut produced);
        }
        events
    }
}

impl Default for SubsystemRegistry {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::world::enums::AgentPhase;
    use std::collections::HashMap;

    fn make_agent(phase: AgentPhase, tokens: u64) -> (Uuid, u64, AgentRecord) {
        (
            Uuid::new_v4(),
            0,
            AgentRecord {
                id: Uuid::new_v4(),
                name: "test".to_string(),
                phase,
                tokens,
                skills: HashMap::new(),
            },
        )
    }

    struct EchoSubsystem {
        n: &'static str,
    }

    impl Subsystem for EchoSubsystem {
        fn name(&self) -> &str {
            self.n
        }

        fn on_tick(
            &self,
            tick: u64,
            _agents: &mut [(Uuid, u64, AgentRecord)],
        ) -> Vec<WorldEvent> {
            vec![WorldEvent::TickAdvanced { tick }]
        }
    }

    #[test]
    fn registry_starts_empty() {
        let r = SubsystemRegistry::new();
        assert!(r.is_empty());
    }

    #[test]
    fn register_and_count() {
        let mut r = SubsystemRegistry::new();
        r.register(Box::new(EchoSubsystem { n: "a" }));
        r.register(Box::new(EchoSubsystem { n: "b" }));
        assert_eq!(r.len(), 2);
    }

    #[test]
    fn run_tick_collects_events_in_order() {
        let mut r = SubsystemRegistry::new();
        r.register(Box::new(EchoSubsystem { n: "first" }));
        r.register(Box::new(EchoSubsystem { n: "second" }));

        let mut agents = vec![make_agent(AgentPhase::Adult, 100)];
        let events = r.run_tick(42, &mut agents);

        assert_eq!(events.len(), 2);
        assert_eq!(events[0], WorldEvent::TickAdvanced { tick: 42 });
        assert_eq!(events[1], WorldEvent::TickAdvanced { tick: 42 });
    }
}
