//! # Agent Diary API
//!
//! REST endpoints for reading agent diary entries.  Diary entries are
//! generated by the agent runtime (Python) after each tick and pushed
//! to the World Engine via the submit endpoint.
//!
//! Endpoints:
//!   - GET    /api/v1/agents/:id/diary          — list entries (query: ?days=7)
//!   - GET    /api/v1/agents/:id/diary/search   — keyword search (query: ?q=...)
//!   - POST   /api/v1/agents/:id/diary          — submit a diary entry

use axum::{
    extract::{Path, Query, State},
    http::StatusCode,
    response::IntoResponse,
    routing::*,
    Json,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tokio::sync::Mutex;

use crate::api::{AppState, ErrorResponse};

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// A single diary entry submitted by an agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiaryEntry {
    pub agent_id: String,
    pub tick: u64,
    pub phase: String,
    pub mood: String,
    pub summary: String,
    #[serde(default)]
    pub key_events: Vec<String>,
    #[serde(default)]
    pub decisions: Vec<String>,
    #[serde(default)]
    pub reflection: String,
    #[serde(default)]
    pub created_at: String,
}

/// In-memory diary store (one per World Engine instance).
///
/// Entries are stored per agent in a Vec, ordered by tick ascending.
/// A configurable per-agent cap prevents unbounded memory growth.
pub struct DiaryStore {
    entries: HashMap<String, Vec<DiaryEntry>>,
    max_per_agent: usize,
}

impl DiaryStore {
    pub fn new(max_per_agent: usize) -> Self {
        Self {
            entries: HashMap::new(),
            max_per_agent,
        }
    }

    /// Append a diary entry for the given agent.
    pub fn push(&mut self, entry: DiaryEntry) {
        let agent_entries = self.entries.entry(entry.agent_id.clone()).or_default();
        agent_entries.push(entry);
        // Evict oldest if over cap
        while agent_entries.len() > self.max_per_agent {
            agent_entries.remove(0);
        }
    }

    /// Get entries for an agent from the last N days.
    pub fn get_recent(
        &self,
        agent_id: &str,
        days: u64,
    ) -> Vec<&DiaryEntry> {
        let cutoff_ts = chrono::Utc::now().timestamp() - (days as i64 * 86400);
        self.entries
            .get(agent_id)
            .map(|entries| {
                entries
                    .iter()
                    .filter(|e| {
                        // Parse created_at and compare
                        chrono::DateTime::parse_from_rfc3339(&e.created_at)
                            .map(|dt| dt.timestamp() >= cutoff_ts)
                            .unwrap_or(true)
                    })
                    .collect()
            })
            .unwrap_or_default()
    }

    /// Search entries by keyword (case-insensitive LIKE match on summary
    /// and reflection).
    pub fn search(
        &self,
        agent_id: &str,
        keyword: &str,
        limit: usize,
    ) -> Vec<&DiaryEntry> {
        let keyword_lower = keyword.to_lowercase();
        self.entries
            .get(agent_id)
            .map(|entries| {
                entries
                    .iter()
                    .rev()
                    .filter(|e| {
                        e.summary.to_lowercase().contains(&keyword_lower)
                            || e.reflection.to_lowercase().contains(&keyword_lower)
                            || e
                                .key_events
                                .iter()
                                .any(|ev| ev.to_lowercase().contains(&keyword_lower))
                    })
                    .take(limit)
                    .collect()
            })
            .unwrap_or_default()
    }

    /// Count entries for an agent.
    pub fn count(&self, agent_id: &str) -> usize {
        self.entries.get(agent_id).map(|e| e.len()).unwrap_or(0)
    }
}

/// Shared diary store type.
pub type SharedDiaryStore = std::sync::Arc<Mutex<DiaryStore>>;

// ---------------------------------------------------------------------------
// Query params
// ---------------------------------------------------------------------------

fn default_days() -> u64 {
    7
}

fn default_limit() -> usize {
    20
}

#[derive(Debug, Deserialize)]
pub struct DiaryQuery {
    #[serde(default = "default_days")]
    pub days: u64,
}

#[derive(Debug, Deserialize)]
pub struct DiarySearchQuery {
    pub q: String,
    #[serde(default = "default_limit")]
    pub limit: usize,
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/// GET /api/v1/agents/:id/diary?days=7
pub async fn list_diary(
    State(state): State<AppState>,
    Path(agent_id): Path<String>,
    Query(query): Query<DiaryQuery>,
) -> impl IntoResponse {
    let store = match &state.diary_store {
        Some(s) => s.clone(),
        None => {
            return (
                StatusCode::SERVICE_UNAVAILABLE,
                Json(ErrorResponse {
                    error: "diary store not configured".into(),
                }),
            )
                .into_response()
        }
    };
    let store = store.lock().await;
    let entries = store.get_recent(&agent_id, query.days);
    Json(entries).into_response()
}

/// GET /api/v1/agents/:id/diary/search?q=keyword
pub async fn search_diary(
    State(state): State<AppState>,
    Path(agent_id): Path<String>,
    Query(query): Query<DiarySearchQuery>,
) -> impl IntoResponse {
    let store = match &state.diary_store {
        Some(s) => s.clone(),
        None => {
            return (
                StatusCode::SERVICE_UNAVAILABLE,
                Json(ErrorResponse {
                    error: "diary store not configured".into(),
                }),
            )
                .into_response()
        }
    };
    let store = store.lock().await;
    let entries = store.search(&agent_id, &query.q, query.limit);
    Json(entries).into_response()
}

/// POST /api/v1/agents/:id/diary
pub async fn submit_diary(
    State(state): State<AppState>,
    Path(agent_id): Path<String>,
    Json(mut entry): Json<DiaryEntry>,
) -> impl IntoResponse {
    let store = match &state.diary_store {
        Some(s) => s.clone(),
        None => {
            return (
                StatusCode::SERVICE_UNAVAILABLE,
                Json(ErrorResponse {
                    error: "diary store not configured".into(),
                }),
            )
                .into_response()
        }
    };
    // Ensure agent_id consistency
    entry.agent_id = agent_id;
    if entry.created_at.is_empty() {
        entry.created_at = chrono::Utc::now().to_rfc3339();
    }
    let mut store = store.lock().await;
    store.push(entry);
    (StatusCode::OK, Json(serde_json::json!({"status": "ok"}))).into_response()
}

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

/// Diary routes.
pub fn diary_routes() -> axum::Router<AppState> {
    axum::Router::new()
        .route("/api/v1/agents/:id/diary", get(list_diary).post(submit_diary))
        .route("/api/v1/agents/:id/diary/search", get(search_diary))
}
