//! Rules subsystem — enforces world rules (R001–R003).
//!
//! Provides a dynamic rule registry and concrete implementations of:
//! - R001: Token consumption (per-tick automatic deduction)
//! - R002: Death judgment (token zero check with grace period)
//! - R003: Newbie protection (first N ticks, cannot be attacked or exploited)

use uuid::Uuid;

use crate::economy::token_burn::{AgentRecord, ConsumptionConfig, TokenBurnEngine};
use crate::lifecycle::{LifecycleConfig, LifecycleMachine, TransitionResult, perform_death_cleanup};
use crate::world::enums::{AgentPhase, DeathReason};
use crate::world::event::WorldEvent;

// ═══════════════════════════════════════════════════════════════════════════
// Rule Context
// ═══════════════════════════════════════════════════════════════════════════

/// Read-only context provided to each rule during evaluation.
/// Contains everything a rule needs to make decisions.
/// Does NOT borrow the agent — data needed from the agent is passed directly.
#[derive(Debug, Clone)]
pub struct RuleContext {
    /// Current world tick.
    pub tick: u64,
    /// The spawn tick of the agent being evaluated.
    pub agent_spawn_tick: u64,
}

impl RuleContext {
    /// Create a new context for the given tick and agent spawn tick.
    pub fn new(tick: u64, agent_spawn_tick: u64) -> Self {
        Self { tick, agent_spawn_tick }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Rule Trait
// ═══════════════════════════════════════════════════════════════════════════

/// A world rule that can be evaluated against an agent.
///
/// Rules are executed in priority order (lower = earlier) during each tick.
/// Each rule returns a list of events it generates.
pub trait Rule: Send + Sync {
    /// Unique rule identifier (e.g. "R001").
    fn id(&self) -> &str;

    /// Human-readable rule name.
    fn name(&self) -> &str;

    /// Execution priority (lower runs first).
    fn priority(&self) -> u32;

    /// Evaluate the rule against the given agent, mutating the agent
    /// and returning any events generated.
    ///
    /// Returns a `RuleResult` with the outcome.
    fn evaluate(&self, ctx: &RuleContext, agent: &mut AgentRecord) -> RuleResult;
}

// ═══════════════════════════════════════════════════════════════════════════
// Rule Result
// ═══════════════════════════════════════════════════════════════════════════

/// Outcome of evaluating a single rule.
#[derive(Debug, Clone)]
pub struct RuleResult {
    /// The rule ID that produced this result.
    pub rule_id: String,
    /// Events generated by this rule.
    pub events: Vec<WorldEvent>,
    /// Whether this rule flagged a violation (for informational purposes).
    pub violated: bool,
}

impl RuleResult {
    /// Create an empty result with no events.
    pub fn empty(rule_id: &str) -> Self {
        Self {
            rule_id: rule_id.to_string(),
            events: Vec::new(),
            violated: false,
        }
    }

    /// Create a result with events.
    pub fn with_events(rule_id: &str, events: Vec<WorldEvent>) -> Self {
        Self {
            rule_id: rule_id.to_string(),
            events,
            violated: false,
        }
    }

    /// Create a violation result.
    pub fn violation(rule_id: &str, event: WorldEvent) -> Self {
        Self {
            rule_id: rule_id.to_string(),
            events: vec![event],
            violated: true,
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Rule Registry
// ═══════════════════════════════════════════════════════════════════════════

/// Dynamic rule registry that manages and executes rules in priority order.
pub struct RuleRegistry {
    rules: Vec<Box<dyn Rule>>,
}

impl RuleRegistry {
    /// Create a new empty registry.
    pub fn new() -> Self {
        Self { rules: Vec::new() }
    }

    /// Register a rule. Rules are kept sorted by priority (ascending).
    pub fn register(&mut self, rule: Box<dyn Rule>) {
        self.rules.push(rule);
        self.rules.sort_by_key(|r| r.priority());
    }

    /// Look up a rule by ID.
    pub fn get(&self, id: &str) -> Option<&dyn Rule> {
        self.rules.iter().find(|r| r.id() == id).map(|r| r.as_ref())
    }

    /// List all registered rule IDs.
    pub fn rule_ids(&self) -> Vec<&str> {
        self.rules.iter().map(|r| r.id()).collect()
    }

    /// Number of registered rules.
    pub fn len(&self) -> usize {
        self.rules.len()
    }

    /// Whether the registry is empty.
    pub fn is_empty(&self) -> bool {
        self.rules.is_empty()
    }

    /// Execute all registered rules against a single agent, in priority order.
    ///
    /// Returns all results produced by all rules.
    pub fn evaluate_agent(
        &self,
        ctx: &RuleContext,
        agent: &mut AgentRecord,
    ) -> Vec<RuleResult> {
        let mut results = Vec::with_capacity(self.rules.len());
        for rule in &self.rules {
            let result = rule.evaluate(ctx, agent);
            results.push(result);
        }
        results
    }

    /// Execute all rules for all agents, collecting results.
    pub fn evaluate_all(
        &self,
        tick: u64,
        agents: &mut [(Uuid, u64, AgentRecord)],
    ) -> Vec<(Uuid, Vec<RuleResult>)> {
        let mut all_results = Vec::new();

        for (agent_id, spawn_tick, agent) in agents.iter_mut() {
            let ctx = RuleContext::new(tick, *spawn_tick);
            let results = self.evaluate_agent(&ctx, agent);
            all_results.push((*agent_id, results));
        }

        all_results
    }
}

impl Default for RuleRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// R001: Token Consumption
// ═══════════════════════════════════════════════════════════════════════════

/// R001: Token consumption rule.
///
/// Each tick, agents lose tokens based on their phase and skills.
/// Uses `TokenBurnEngine` for the actual calculation.
pub struct TokenConsumptionRule {
    engine: TokenBurnEngine,
}

impl TokenConsumptionRule {
    /// Create with default consumption config.
    pub fn new() -> Self {
        Self {
            engine: TokenBurnEngine::with_defaults(),
        }
    }

    /// Create with custom consumption config.
    pub fn with_config(config: ConsumptionConfig) -> Self {
        Self {
            engine: TokenBurnEngine::new(config),
        }
    }

    /// Get a reference to the underlying engine.
    pub fn engine(&self) -> &TokenBurnEngine {
        &self.engine
    }
}

impl Default for TokenConsumptionRule {
    fn default() -> Self {
        Self::new()
    }
}

impl Rule for TokenConsumptionRule {
    fn id(&self) -> &str {
        "R001"
    }

    fn name(&self) -> &str {
        "Token Consumption"
    }

    fn priority(&self) -> u32 {
        100
    }

    fn evaluate(&self, _ctx: &RuleContext, agent: &mut AgentRecord) -> RuleResult {
        // Skip dead or birth-phase agents
        if agent.phase == AgentPhase::Dead || agent.phase == AgentPhase::Birth {
            return RuleResult::empty(self.id());
        }

        let burn_amount = self.engine.calculate_tick_burn(agent);
        if burn_amount == 0 {
            return RuleResult::empty(self.id());
        }

        let tokens_before = agent.tokens;
        let actual_burn = burn_amount.min(agent.tokens);
        agent.tokens -= actual_burn;

        let mut events = Vec::new();

        if actual_burn > 0 {
            events.push(WorldEvent::BalanceChanged {
                agent_id: agent.id.to_string(),
                currency: crate::world::enums::Currency::Token,
                old_balance: tokens_before,
                new_balance: agent.tokens,
            });
        }

        RuleResult::with_events(self.id(), events)
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// R002: Death Judgment
// ═══════════════════════════════════════════════════════════════════════════

/// R002: Death judgment rule.
///
/// Checks if an agent's tokens have reached zero. When tokens are depleted,
/// the agent transitions through dying -> dead phases.
pub struct DeathJudgmentRule {
    /// Number of grace ticks after tokens hit zero before actual death.
    pub grace_ticks: u64,
}

impl DeathJudgmentRule {
    /// Create with default grace period (0 ticks = immediate death).
    pub fn new() -> Self {
        Self { grace_ticks: 0 }
    }

    /// Create with a custom grace period.
    pub fn with_grace_ticks(grace_ticks: u64) -> Self {
        Self { grace_ticks }
    }
}

impl Default for DeathJudgmentRule {
    fn default() -> Self {
        Self::new()
    }
}

impl Rule for DeathJudgmentRule {
    fn id(&self) -> &str {
        "R002"
    }

    fn name(&self) -> &str {
        "Death Judgment"
    }

    fn priority(&self) -> u32 {
        200
    }

    fn evaluate(&self, _ctx: &RuleContext, agent: &mut AgentRecord) -> RuleResult {
        // Skip agents already dead
        if agent.phase == AgentPhase::Dead {
            return RuleResult::empty(self.id());
        }

        // Skip birth-phase agents (protected)
        if agent.phase == AgentPhase::Birth {
            return RuleResult::empty(self.id());
        }

        // Check if tokens are depleted
        if agent.tokens > 0 {
            return RuleResult::empty(self.id());
        }

        let mut events = Vec::new();

        // Agent is dying
        events.push(WorldEvent::AgentDying {
            agent_id: agent.id.to_string(),
            reason: DeathReason::TokenDepleted,
            grace_ticks: self.grace_ticks,
        });

        // If grace period is 0, immediately transition to dead
        if self.grace_ticks == 0 {
            agent.phase = AgentPhase::Dead;
            events.push(WorldEvent::AgentDied {
                agent_id: agent.id.to_string(),
                reason: DeathReason::TokenDepleted,
            });
        }
        // If grace > 0, the agent enters Dying phase and will be
        // fully killed after grace_ticks have elapsed (handled externally
        // or by a future grace-tracking mechanism).

        RuleResult::with_events(self.id(), events)
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// R003: Newbie Protection
// ═══════════════════════════════════════════════════════════════════════════

/// R003: Newbie protection rule.
///
/// Agents in their first `protection_ticks` ticks cannot be attacked
/// or exploited. This rule validates actions against protected agents
/// and emits violation events when the protection is breached.
pub struct NewbieProtectionRule {
    /// Number of ticks after spawn during which the agent is protected.
    pub protection_ticks: u64,
}

impl NewbieProtectionRule {
    /// Create with default protection duration (50 ticks).
    pub fn new() -> Self {
        Self {
            protection_ticks: 50,
        }
    }

    /// Create with custom protection duration.
    pub fn with_protection_ticks(ticks: u64) -> Self {
        Self {
            protection_ticks: ticks,
        }
    }

    /// Check whether an agent is currently under protection.
    pub fn is_protected(&self, agent: &AgentRecord, current_tick: u64, spawn_tick: u64) -> bool {
        if agent.phase == AgentPhase::Dead {
            return false;
        }
        let age = current_tick.saturating_sub(spawn_tick);
        age < self.protection_ticks
    }

    /// Check if a target agent is protected and, if so, return a violation event.
    /// Call this before performing any hostile action against a target agent.
    pub fn check_attack(
        &self,
        attacker_id: &Uuid,
        target: &AgentRecord,
        current_tick: u64,
        spawn_tick: u64,
        action: &str,
    ) -> Option<WorldEvent> {
        if self.is_protected(target, current_tick, spawn_tick) {
            Some(WorldEvent::RuleViolated {
                agent_id: attacker_id.to_string(),
                rule: "R003".to_string(),
                details: format!(
                    "Cannot {} against protected agent '{}' (age: {}/{} ticks)",
                    action,
                    target.name,
                    current_tick.saturating_sub(spawn_tick),
                    self.protection_ticks,
                ),
            })
        } else {
            None
        }
    }
}

impl Default for NewbieProtectionRule {
    fn default() -> Self {
        Self::new()
    }
}

impl Rule for NewbieProtectionRule {
    fn id(&self) -> &str {
        "R003"
    }

    fn name(&self) -> &str {
        "Newbie Protection"
    }

    fn priority(&self) -> u32 {
        50 // Runs before token consumption and death
    }

    fn evaluate(&self, ctx: &RuleContext, agent: &mut AgentRecord) -> RuleResult {
        // This rule is primarily used via `check_attack` for action validation.
        // During tick evaluation, it sets the agent's phase to Childhood
        // if still within the protection window and phase is Birth.
        if agent.phase == AgentPhase::Dead {
            return RuleResult::empty(self.id());
        }

        let age = ctx.tick.saturating_sub(ctx.agent_spawn_tick);

        // If within protection window, ensure agent is in a protected state
        if age < self.protection_ticks && agent.phase == AgentPhase::Birth {
            // Transition Birth -> Childhood when protection starts
            let old_phase = agent.phase;
            agent.phase = AgentPhase::Childhood;
            return RuleResult::with_events(
                self.id(),
                vec![WorldEvent::PhaseChanged {
                    agent_id: agent.id.to_string(),
                    old_phase,
                    new_phase: AgentPhase::Childhood,
                }],
            );
        }

        RuleResult::empty(self.id())
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// R004: Aging Transition
// ═══════════════════════════════════════════════════════════════════════════

/// R004: Aging transition rule.
///
/// Checks tick-based phase transitions (Childhood→Adult, Adult→Elder, Elder→Dead).
/// Uses `LifecycleMachine` for transition logic and emits PhaseChanged events.
pub struct AgingTransitionRule {
    machine: LifecycleMachine,
}

impl AgingTransitionRule {
    /// Create with default lifecycle config.
    pub fn new() -> Self {
        Self {
            machine: LifecycleMachine::with_defaults(),
        }
    }

    /// Create with custom lifecycle config.
    pub fn with_config(config: LifecycleConfig) -> Self {
        Self {
            machine: LifecycleMachine::new(config),
        }
    }
}

impl Default for AgingTransitionRule {
    fn default() -> Self {
        Self::new()
    }
}

impl Rule for AgingTransitionRule {
    fn id(&self) -> &str {
        "R004"
    }

    fn name(&self) -> &str {
        "Aging Transition"
    }

    fn priority(&self) -> u32 {
        75 // After protection (50), before token burn (100)
    }

    fn evaluate(&self, ctx: &RuleContext, agent: &mut AgentRecord) -> RuleResult {
        let transition = self.machine.evaluate_aging(ctx.tick, ctx.agent_spawn_tick, agent);

        match transition {
            TransitionResult::NoTransition => RuleResult::empty(self.id()),
            TransitionResult::PhaseChanged { .. } => {
                let events = self.machine.events_for_transition(agent, &transition);
                RuleResult::with_events(self.id(), events)
            }
            TransitionResult::Died { .. } => {
                let mut events = self.machine.events_for_transition(agent, &transition);

                // Perform death cleanup
                let cleanup = perform_death_cleanup(agent);
                agent.phase = AgentPhase::Dead;
                events.extend(cleanup.events);

                RuleResult::with_events(self.id(), events)
            }
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Convenience: Default Registry Builder
// ═══════════════════════════════════════════════════════════════════════════

/// Build a `RuleRegistry` pre-loaded with the standard R001-R004 rules.
pub fn default_registry() -> RuleRegistry {
    let mut registry = RuleRegistry::new();
    registry.register(Box::new(NewbieProtectionRule::new()));
    registry.register(Box::new(AgingTransitionRule::new()));
    registry.register(Box::new(TokenConsumptionRule::new()));
    registry.register(Box::new(DeathJudgmentRule::new()));
    registry
}

/// Build a `RuleRegistry` with custom config.
pub fn custom_registry(
    consumption_config: ConsumptionConfig,
    grace_ticks: u64,
    protection_ticks: u64,
) -> RuleRegistry {
    let mut registry = RuleRegistry::new();
    registry.register(Box::new(NewbieProtectionRule::with_protection_ticks(protection_ticks)));
    registry.register(Box::new(AgingTransitionRule::new()));
    registry.register(Box::new(TokenConsumptionRule::with_config(consumption_config)));
    registry.register(Box::new(DeathJudgmentRule::with_grace_ticks(grace_ticks)));
    registry
}

// ═══════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn make_agent(phase: AgentPhase, tokens: u64) -> AgentRecord {
        AgentRecord {
            id: Uuid::new_v4(),
            name: "test-agent".to_string(),
            phase,
            tokens,
            skills: HashMap::new(),
        }
    }

    fn make_agent_named(name: &str, phase: AgentPhase, tokens: u64) -> AgentRecord {
        AgentRecord {
            id: Uuid::new_v4(),
            name: name.to_string(),
            phase,
            tokens,
            skills: HashMap::new(),
        }
    }

    // ── Rule Registry tests ──

    #[test]
    fn test_registry_starts_empty() {
        let registry = RuleRegistry::new();
        assert!(registry.is_empty());
        assert_eq!(registry.len(), 0);
    }

    #[test]
    fn test_default_registry_has_four_rules() {
        let registry = default_registry();
        assert_eq!(registry.len(), 4);
        assert!(registry.get("R001").is_some());
        assert!(registry.get("R002").is_some());
        assert!(registry.get("R003").is_some());
        assert!(registry.get("R004").is_some());
    }

    #[test]
    fn test_rules_sorted_by_priority() {
        let registry = default_registry();
        let ids = registry.rule_ids();
        // R003(50), R004(75), R001(100), R002(200)
        assert_eq!(ids, vec!["R003", "R004", "R001", "R002"]);
    }

    #[test]
    fn test_get_rule_by_id() {
        let registry = default_registry();
        let r001 = registry.get("R001").unwrap();
        assert_eq!(r001.id(), "R001");
        assert_eq!(r001.name(), "Token Consumption");
    }

    #[test]
    fn test_get_nonexistent_rule() {
        let registry = default_registry();
        assert!(registry.get("R999").is_none());
    }

    #[test]
    fn test_custom_registry() {
        let registry = custom_registry(ConsumptionConfig::default(), 5, 100);
        assert_eq!(registry.len(), 4);
    }

    // ── R001: Token Consumption tests ──

    #[test]
    fn test_r001_adult_burns_tokens() {
        let rule = TokenConsumptionRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 100);
        let ctx = RuleContext::new(1, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.rule_id, "R001");
        assert!(!result.violated);
        assert_eq!(agent.tokens, 90); // 100 - 10 (default adult burn)
        assert_eq!(result.events.len(), 1);

        match &result.events[0] {
            WorldEvent::BalanceChanged { agent_id, currency, old_balance, new_balance } => {
                assert_eq!(*agent_id, agent.id.to_string());
                assert_eq!(*currency, crate::world::enums::Currency::Token);
                assert_eq!(*old_balance, 100);
                assert_eq!(*new_balance, 90);
            }
            _ => panic!("Expected BalanceChanged event"),
        }
    }

    #[test]
    fn test_r001_skips_dead_agents() {
        let rule = TokenConsumptionRule::new();
        let mut agent = make_agent(AgentPhase::Dead, 100);
        let ctx = RuleContext::new(1, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.events.len(), 0);
        assert_eq!(agent.tokens, 100); // Unchanged
    }

    #[test]
    fn test_r001_skips_birth_agents() {
        let rule = TokenConsumptionRule::new();
        let mut agent = make_agent(AgentPhase::Birth, 100);
        let ctx = RuleContext::new(1, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.events.len(), 0);
        assert_eq!(agent.tokens, 100);
    }

    #[test]
    fn test_r001_clamps_to_zero() {
        let rule = TokenConsumptionRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 3); // Only 3 tokens, burn is 10
        let ctx = RuleContext::new(1, 0);

        let _ = rule.evaluate(&ctx, &mut agent);

        assert_eq!(agent.tokens, 0);
    }

    #[test]
    fn test_r001_at_zero_no_event() {
        let rule = TokenConsumptionRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 0);
        let ctx = RuleContext::new(1, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(agent.tokens, 0);
        assert_eq!(result.events.len(), 0); // No change, no event
    }

    #[test]
    fn test_r001_childhood_burns_less() {
        let rule = TokenConsumptionRule::new();
        let mut agent = make_agent(AgentPhase::Childhood, 100);
        let ctx = RuleContext::new(1, 0);

        rule.evaluate(&ctx, &mut agent);

        // childhood multiplier is 0.5, so burn = 10 * 0.5 = 5
        assert_eq!(agent.tokens, 95);
    }

    #[test]
    fn test_r001_elder_burns_less() {
        let rule = TokenConsumptionRule::new();
        let mut agent = make_agent(AgentPhase::Elder, 100);
        let ctx = RuleContext::new(1, 0);

        rule.evaluate(&ctx, &mut agent);

        // elder multiplier is 0.7, so burn = 10 * 0.7 = 7
        assert_eq!(agent.tokens, 93);
    }

    // ── R002: Death Judgment tests ──

    #[test]
    fn test_r002_kills_agent_at_zero_tokens() {
        let rule = DeathJudgmentRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 0);
        let ctx = RuleContext::new(10, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.rule_id, "R002");
        assert_eq!(agent.phase, AgentPhase::Dead);

        // Should emit AgentDying and AgentDied
        assert_eq!(result.events.len(), 2);
        assert!(matches!(&result.events[0], WorldEvent::AgentDying { .. }));
        assert!(matches!(&result.events[1], WorldEvent::AgentDied { reason: DeathReason::TokenDepleted, .. }));
    }

    #[test]
    fn test_r002_skips_agent_with_tokens() {
        let rule = DeathJudgmentRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 50);
        let ctx = RuleContext::new(10, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.events.len(), 0);
        assert_eq!(agent.phase, AgentPhase::Adult);
    }

    #[test]
    fn test_r002_skips_dead_agents() {
        let rule = DeathJudgmentRule::new();
        let mut agent = make_agent(AgentPhase::Dead, 0);
        let ctx = RuleContext::new(10, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.events.len(), 0);
    }

    #[test]
    fn test_r002_skips_birth_agents() {
        let rule = DeathJudgmentRule::new();
        let mut agent = make_agent(AgentPhase::Birth, 0);
        let ctx = RuleContext::new(1, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.events.len(), 0);
        assert_ne!(agent.phase, AgentPhase::Dead);
    }

    #[test]
    fn test_r002_with_grace_period() {
        let rule = DeathJudgmentRule::with_grace_ticks(10);
        let mut agent = make_agent(AgentPhase::Adult, 0);
        let ctx = RuleContext::new(10, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        // Should emit AgentDying but NOT AgentDied (grace period)
        assert_eq!(result.events.len(), 1);
        assert!(matches!(&result.events[0], WorldEvent::AgentDying { grace_ticks: 10, .. }));
        assert_ne!(agent.phase, AgentPhase::Dead); // Not yet dead
    }

    #[test]
    fn test_r002_death_reason_is_token_depleted() {
        let rule = DeathJudgmentRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 0);
        let ctx = RuleContext::new(5, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        let died_event = result.events.iter().find(|e| matches!(e, WorldEvent::AgentDied { .. }));
        assert!(died_event.is_some());
        if let Some(WorldEvent::AgentDied { reason, .. }) = died_event {
            assert_eq!(*reason, DeathReason::TokenDepleted);
        }
    }

    // ── R003: Newbie Protection tests ──

    #[test]
    fn test_r003_default_protection_is_50_ticks() {
        let rule = NewbieProtectionRule::new();
        assert_eq!(rule.protection_ticks, 50);
    }

    #[test]
    fn test_r003_agent_is_protected_within_window() {
        let rule = NewbieProtectionRule::new();
        let agent = make_agent(AgentPhase::Adult, 100);

        assert!(rule.is_protected(&agent, 0, 0));
        assert!(rule.is_protected(&agent, 25, 0));
        assert!(rule.is_protected(&agent, 49, 0));
        assert!(!rule.is_protected(&agent, 50, 0)); // Exactly at boundary -- NOT protected
        assert!(!rule.is_protected(&agent, 51, 0));
        assert!(!rule.is_protected(&agent, 100, 0));
    }

    #[test]
    fn test_r003_agent_is_protected_with_spawn_offset() {
        let rule = NewbieProtectionRule::new();
        let agent = make_agent(AgentPhase::Adult, 100);

        // Spawned at tick 10, protection lasts until tick 60
        assert!(rule.is_protected(&agent, 10, 10));
        assert!(rule.is_protected(&agent, 59, 10));
        assert!(!rule.is_protected(&agent, 60, 10));
    }

    #[test]
    fn test_r003_dead_agent_not_protected() {
        let rule = NewbieProtectionRule::new();
        let agent = make_agent(AgentPhase::Dead, 0);

        assert!(!rule.is_protected(&agent, 5, 0));
    }

    #[test]
    fn test_r003_check_attack_blocks_during_protection() {
        let rule = NewbieProtectionRule::new();
        let attacker_id = Uuid::new_v4();
        let target = make_agent(AgentPhase::Adult, 100);

        // Attack at tick 10 (within protection)
        let result = rule.check_attack(&attacker_id, &target, 10, 0, "attack");
        assert!(result.is_some());

        if let Some(WorldEvent::RuleViolated { agent_id, rule: rule_id, details }) = &result {
            assert_eq!(*agent_id, attacker_id.to_string());
            assert_eq!(rule_id, "R003");
            assert!(details.contains("protected"));
        } else {
            panic!("Expected RuleViolated event");
        }
    }

    #[test]
    fn test_r003_check_attack_allows_after_protection() {
        let rule = NewbieProtectionRule::new();
        let attacker_id = Uuid::new_v4();
        let target = make_agent(AgentPhase::Adult, 100);

        // Attack at tick 50 (protection expired)
        let result = rule.check_attack(&attacker_id, &target, 50, 0, "attack");
        assert!(result.is_none());
    }

    #[test]
    fn test_r003_evaluate_transitions_birth_to_childhood() {
        let rule = NewbieProtectionRule::new();
        let mut agent = make_agent(AgentPhase::Birth, 100);
        let ctx = RuleContext::new(1, 1);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(agent.phase, AgentPhase::Childhood);
        assert_eq!(result.events.len(), 1);

        match &result.events[0] {
            WorldEvent::PhaseChanged { old_phase, new_phase, .. } => {
                assert_eq!(*old_phase, AgentPhase::Birth);
                assert_eq!(*new_phase, AgentPhase::Childhood);
            }
            _ => panic!("Expected PhaseChanged event"),
        }
    }

    #[test]
    fn test_r003_evaluate_no_transition_if_already_childhood() {
        let rule = NewbieProtectionRule::new();
        let mut agent = make_agent(AgentPhase::Childhood, 100);
        let ctx = RuleContext::new(5, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.events.len(), 0);
        assert_eq!(agent.phase, AgentPhase::Childhood);
    }

    #[test]
    fn test_r003_custom_protection_ticks() {
        let rule = NewbieProtectionRule::with_protection_ticks(100);
        assert_eq!(rule.protection_ticks, 100);

        let agent = make_agent(AgentPhase::Adult, 100);
        assert!(rule.is_protected(&agent, 99, 0));
        assert!(!rule.is_protected(&agent, 100, 0));
    }

    // ── Integration: evaluate_agent with all rules ──

    #[test]
    fn test_evaluate_agent_living_adult() {
        let registry = default_registry();
        let mut agent = make_agent(AgentPhase::Adult, 100);
        let ctx = RuleContext::new(1, 0);

        let results = registry.evaluate_agent(&ctx, &mut agent);

        assert_eq!(results.len(), 4);

        // R003: No phase change (already Adult)
        assert_eq!(results[0].rule_id, "R003");
        assert!(results[0].events.is_empty());

        // R004: No aging transition (adult, tick 1)
        let r004 = results.iter().find(|r| r.rule_id == "R004").unwrap();
        assert!(r004.events.is_empty());

        // R001: Token burn
        let _r001 = results.iter().find(|r| r.rule_id == "R001").unwrap();
        assert_eq!(agent.tokens, 90);

        // R002: No death
        let r002 = results.iter().find(|r| r.rule_id == "R002").unwrap();
        assert!(r002.events.is_empty());
    }

    #[test]
    fn test_evaluate_agent_dies_when_tokens_reach_zero() {
        let registry = default_registry();
        let mut agent = make_agent(AgentPhase::Adult, 10);
        let ctx = RuleContext::new(1, 0);

        // Burn 10 tokens
        let results = registry.evaluate_agent(&ctx, &mut agent);

        assert_eq!(agent.tokens, 0);

        // Find R001 result -- should have burned all tokens
        let r001 = results.iter().find(|r| r.rule_id == "R001").unwrap();
        assert_eq!(r001.events.len(), 1);

        // Find R002 result -- should have killed the agent
        let r002 = results.iter().find(|r| r.rule_id == "R002").unwrap();
        assert_eq!(r002.events.len(), 2); // AgentDying + AgentDied
        assert_eq!(agent.phase, AgentPhase::Dead);
    }

    #[test]
    fn test_evaluate_all_multiple_agents() {
        let registry = default_registry();
        let id1 = Uuid::new_v4();
        let id2 = Uuid::new_v4();

        let mut agents: Vec<(Uuid, u64, AgentRecord)> = vec![
            (id1, 0, make_agent(AgentPhase::Adult, 100)),
            (id2, 0, make_agent(AgentPhase::Adult, 5)),
        ];

        let results = registry.evaluate_all(1, &mut agents);

        assert_eq!(results.len(), 2);

        // Agent 1 should survive with 90 tokens
        assert_eq!(agents[0].2.tokens, 90);
        assert_eq!(agents[0].2.phase, AgentPhase::Adult);

        // Agent 2 should die (5 tokens, burn 10, clamped to 0)
        assert_eq!(agents[1].2.tokens, 0);
        assert_eq!(agents[1].2.phase, AgentPhase::Dead);
    }

    #[test]
    fn test_multi_tick_death_flow() {
        let rule_r001 = TokenConsumptionRule::new();
        let rule_r002 = DeathJudgmentRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 30);

        // Tick 1: 30 -> 20
        let ctx = RuleContext::new(1, 0);
        rule_r001.evaluate(&ctx, &mut agent);
        rule_r002.evaluate(&ctx, &mut agent);
        assert_eq!(agent.tokens, 20);
        assert_eq!(agent.phase, AgentPhase::Adult);

        // Tick 2: 20 -> 10
        let ctx = RuleContext::new(2, 0);
        rule_r001.evaluate(&ctx, &mut agent);
        rule_r002.evaluate(&ctx, &mut agent);
        assert_eq!(agent.tokens, 10);
        assert_eq!(agent.phase, AgentPhase::Adult);

        // Tick 3: 10 -> 0, then death
        let ctx = RuleContext::new(3, 0);
        rule_r001.evaluate(&ctx, &mut agent);
        assert_eq!(agent.tokens, 0);
        rule_r002.evaluate(&ctx, &mut agent);
        assert_eq!(agent.phase, AgentPhase::Dead);

        // Tick 4: Dead agent stays dead, no burn
        let ctx = RuleContext::new(4, 0);
        rule_r001.evaluate(&ctx, &mut agent);
        assert_eq!(agent.tokens, 0); // No further burn
        rule_r002.evaluate(&ctx, &mut agent);
        assert_eq!(agent.phase, AgentPhase::Dead);
    }

    #[test]
    fn test_newbie_protection_prevents_attack() {
        let protection = NewbieProtectionRule::new();
        let attacker_id = Uuid::new_v4();
        let target = make_agent(AgentPhase::Childhood, 100);

        // Within protection: tick 25, spawned at 0 -> age 25 < 50
        let violation = protection.check_attack(&attacker_id, &target, 25, 0, "steal");
        assert!(violation.is_some());

        // Outside protection: tick 50, spawned at 0 -> age 50 >= 50
        let no_violation = protection.check_attack(&attacker_id, &target, 50, 0, "steal");
        assert!(no_violation.is_none());
    }

    #[test]
    fn test_newbie_protection_exact_boundary() {
        let protection = NewbieProtectionRule::with_protection_ticks(50);
        let agent = make_agent(AgentPhase::Adult, 100);

        // tick 49, spawn 0 -> age 49 -> protected
        assert!(protection.is_protected(&agent, 49, 0));
        // tick 50, spawn 0 -> age 50 -> NOT protected (age >= protection_ticks)
        assert!(!protection.is_protected(&agent, 50, 0));
    }

    #[test]
    fn test_violation_event_details() {
        let protection = NewbieProtectionRule::new();
        let attacker_id = Uuid::new_v4();
        let target = make_agent_named("Alice", AgentPhase::Adult, 100);

        let event = protection.check_attack(&attacker_id, &target, 25, 0, "exploit");
        assert!(event.is_some());

        if let Some(WorldEvent::RuleViolated { details, .. }) = &event {
            assert!(details.contains("exploit"));
            assert!(details.contains("Alice"));
            assert!(details.contains("25/50"));
        }
    }

    #[test]
    fn test_r001_with_skills() {
        use crate::economy::token_burn::SkillRecord;

        let rule = TokenConsumptionRule::new();
        let mut agent = AgentRecord {
            id: Uuid::new_v4(),
            name: "skilled".to_string(),
            phase: AgentPhase::Adult,
            tokens: 100,
            skills: vec![
                ("mining".to_string(), SkillRecord { name: "mining".to_string(), level: 5, experience: 0.0 }),
            ].into_iter().collect(),
        };

        let ctx = RuleContext::new(1, 0);
        rule.evaluate(&ctx, &mut agent);

        // base=10 * 1.0 + skill: 5 * 0.5 = 10 + 2.5 = 12 (truncated)
        assert_eq!(agent.tokens, 88);
    }

    #[test]
    fn test_full_lifecycle_with_protection() {
        // Spawn at Birth, protected for 50 ticks, then transitions
        let registry = default_registry();
        let mut agent = make_agent(AgentPhase::Birth, 500);
        // Spawn at tick 0, evaluate at tick 1 -> should transition to Childhood
        let ctx = RuleContext::new(1, 0);
        let results = registry.evaluate_agent(&ctx, &mut agent);

        assert_eq!(agent.phase, AgentPhase::Childhood); // R003 transitioned
        // Childhood burn: base=10 * 0.5 = 5
        assert_eq!(agent.tokens, 495);
        assert_eq!(agent.phase, AgentPhase::Childhood); // Still alive

        // Verify R003 produced a PhaseChanged event
        let r003 = results.iter().find(|r| r.rule_id == "R003").unwrap();
        assert_eq!(r003.events.len(), 1);
    }

    // ── R004: Aging Transition tests ──

    #[test]
    fn test_r004_no_transition_for_adult_early() {
        let rule = AgingTransitionRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 500);
        let ctx = RuleContext::new(500, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(result.rule_id, "R004");
        assert!(result.events.is_empty());
        assert_eq!(agent.phase, AgentPhase::Adult);
    }

    #[test]
    fn test_r004_childhood_to_adult() {
        let rule = AgingTransitionRule::new();
        let mut agent = make_agent(AgentPhase::Childhood, 500);
        // childhood_end_tick(0) = 101
        let ctx = RuleContext::new(101, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(agent.phase, AgentPhase::Adult);
        assert_eq!(result.events.len(), 1);
        assert!(matches!(&result.events[0], WorldEvent::PhaseChanged {
            old_phase: AgentPhase::Childhood,
            new_phase: AgentPhase::Adult,
            ..
        }));
    }

    #[test]
    fn test_r004_adult_to_elder() {
        let rule = AgingTransitionRule::new();
        let mut agent = make_agent(AgentPhase::Adult, 500);
        // adult_end_tick(0) = 1101
        let ctx = RuleContext::new(1101, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(agent.phase, AgentPhase::Elder);
        assert_eq!(result.events.len(), 1);
        assert!(matches!(&result.events[0], WorldEvent::PhaseChanged {
            old_phase: AgentPhase::Adult,
            new_phase: AgentPhase::Elder,
            ..
        }));
    }

    #[test]
    fn test_r004_elder_natural_death_with_cleanup() {
        let rule = AgingTransitionRule::new();
        let mut agent = make_agent(AgentPhase::Elder, 250);
        // elder_end_tick(0) = 1301
        let ctx = RuleContext::new(1301, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert_eq!(agent.phase, AgentPhase::Dead);
        assert_eq!(agent.tokens, 0); // Cleanup destroyed tokens
        assert!(!result.events.is_empty());

        // Should contain: AgentDying + PhaseChanged + BalanceChanged + AgentDied
        let has_dying = result.events.iter().any(|e| matches!(e, WorldEvent::AgentDying { .. }));
        let has_died = result.events.iter().any(|e| matches!(e, WorldEvent::AgentDied { .. }));
        let has_phase = result.events.iter().any(|e| matches!(e, WorldEvent::PhaseChanged { .. }));
        let has_balance = result.events.iter().any(|e| matches!(e, WorldEvent::BalanceChanged { .. }));
        assert!(has_dying);
        assert!(has_died);
        assert!(has_phase);
        assert!(has_balance);
    }

    #[test]
    fn test_r004_skips_dead() {
        let rule = AgingTransitionRule::new();
        let mut agent = make_agent(AgentPhase::Dead, 0);
        let ctx = RuleContext::new(9999, 0);

        let result = rule.evaluate(&ctx, &mut agent);

        assert!(result.events.is_empty());
        assert_eq!(agent.phase, AgentPhase::Dead);
    }

    #[test]
    fn test_r004_integration_full_lifecycle_through_registry() {
        let registry = default_registry();

        // Start at Childhood, spawn at tick 0
        let mut agent = make_agent(AgentPhase::Childhood, 5000);

        // Tick 50: still Childhood
        let ctx = RuleContext::new(50, 0);
        registry.evaluate_agent(&ctx, &mut agent);
        assert_eq!(agent.phase, AgentPhase::Childhood);

        // Tick 101: Childhood -> Adult (R004)
        let ctx = RuleContext::new(101, 0);
        registry.evaluate_agent(&ctx, &mut agent);
        assert_eq!(agent.phase, AgentPhase::Adult);

        // Tick 500: still Adult
        let ctx = RuleContext::new(500, 0);
        registry.evaluate_agent(&ctx, &mut agent);
        assert_eq!(agent.phase, AgentPhase::Adult);

        // Tick 1101: Adult -> Elder (R004)
        let ctx = RuleContext::new(1101, 0);
        registry.evaluate_agent(&ctx, &mut agent);
        assert_eq!(agent.phase, AgentPhase::Elder);

        // Tick 1301: Elder -> Dead (R004 natural death)
        let ctx = RuleContext::new(1301, 0);
        registry.evaluate_agent(&ctx, &mut agent);
        assert_eq!(agent.phase, AgentPhase::Dead);
    }
}
