/**
 * Data loading utilities.
 *
 * Loads real JSON data from public/data/ (generated by SEN-239).
 * Each loader maps the backend JSON format to the frontend DemoData types.
 * Falls back to mock data if loading fails.
 */

import type {
  DemoAgent,
  DemoOrganization,
  EmergenceEvent,
  MetricSeries,
  SandboxTemplate,
  ValueProfile,
  WorldSnapshot,
} from "@/types/demo";
import { getMockData, SANDBOX_TEMPLATES } from "./mock-data";

const USE_REAL_DATA = true;

// ── Raw JSON types (backend format from generate_demo_data.py) ─────

interface RawAgent {
  id: string;
  name: string;
  phase: string;
  money: number;
  tokens: number;
  reputation: number;
  personality_traits: {
    openness: number;
    conscientiousness: number;
    extraversion: number;
    agreeableness: number;
    neuroticism: number;
  };
  values: string[];
  skills: Record<string, number>;
  relationships: {
    target_id: string;
    target_name: string;
    type: string;
    strength: number;
  }[];
  memories: string[];
  birth_tick: number;
  death_tick: number | null;
  alive: boolean;
}

interface RawEvent {
  id: string;
  tick: number;
  type: string;
  title: string;
  description: string;
  involved_agents: { id: string; name: string }[];
  involved_orgs: { id: string; name: string }[];
}

interface RawSnapshot {
  tick: number;
  timestamp: number;
  total_population: number;
  active_agents: number;
  gdp: number;
  gini_coefficient: number;
  skill_distribution_top5: {
    skill_name: string;
    agent_count: number;
    avg_level: number;
  }[];
  key_events: {
    tick: number;
    event_type: string;
    agent_id: string | null;
    description: string;
  }[];
}

interface RawMetricPoint {
  tick: number;
  value: number;
}

interface RawMetrics {
  cultural_diversity: RawMetricPoint[];
  organization_count: RawMetricPoint[];
  economic_activity: { tick: number; trade_volume: number; gdp: number }[];
  governance_events: { tick: number; proposals: number; votes_cast: number }[];
}

interface RawOrganization {
  id: string;
  name: string;
  type: string;
  status: string;
  treasury: number;
  debts: number;
  member_count: number;
  members: {
    agent_id: string;
    agent_name: string;
    role: string;
    share: number;
    joined_tick: number;
  }[];
  created_tick: number;
  last_activity_tick: number;
}

// ── Helpers ────────────────────────────────────────────────────────

const EMOJIS = [
  "🤖", "🧠", "💡", "🔮", "⚡", "🌟", "🎯", "🔬",
  "🛡️", "⚔️", "📚", "🎭", "🏦", "⚗️", "🧭", "🎪",
  "🦊", "🐺", "🦅", "🐉", "🌊", "🔥", "❄️", "🌿",
  "💎", "🌈", "🎸", "🚀", "🧩", "🗝️", "🏹", "🛡️",
  "♟️", "🎪", "🏔️", "🌊", "🍂", "🌅", "💫", "🪐",
  "🦉", "🐝", "🦋", "🐙", "🌸", "🍀", "🦇", "🐋",
];

function getPhaseForTick(tick: number): "exploration" | "organization" | "governance" {
  if (tick < 500) return "exploration";
  if (tick < 2000) return "organization";
  return "governance";
}

function mapAgentType(raw: string): "ally" | "rival" | "trade_partner" | "mentor" | "student" {
  if (raw === "friend" || raw === "ally") return "ally";
  if (raw === "trade_partner") return "trade_partner";
  if (raw === "rival") return "rival";
  if (raw === "mentor") return "mentor";
  if (raw === "student") return "student";
  return "ally";
}

function mapEventType(raw: string): "organization" | "trade" | "governance" | "culture" {
  if (raw === "organization") return "organization";
  if (raw === "economic" || raw === "milestone") return "trade";
  if (raw === "governance") return "governance";
  if (raw === "cultural") return "culture";
  return "culture";
}

const DEFAULT_VALUES: ValueProfile = {
  survival: 0.5, power: 0.5, freedom: 0.5,
  knowledge: 0.5, cooperation: 0.5, tradition: 0.5,
};

// ── Adapters ───────────────────────────────────────────────────────

function adaptAgent(raw: RawAgent, index: number, orgLookup: Map<string, string>): DemoAgent {
  // Map Chinese value names to value profile keys
  const values: ValueProfile = { ...DEFAULT_VALUES };
  const valueKeyMap: Record<string, keyof ValueProfile> = {
    "生存": "survival", "权力": "power", "自由": "freedom",
    "知识": "knowledge", "合作": "cooperation", "传统": "tradition",
    "平等": "cooperation", "团结": "cooperation", "智慧": "knowledge",
    "博爱": "cooperation", "仁慈": "cooperation", "诚实": "tradition",
    "正义": "power", "勇气": "survival", "忠诚": "tradition",
    "创新": "knowledge", "和谐": "cooperation", "荣誉": "tradition",
  };
  raw.values.forEach((v, i) => {
    const key = valueKeyMap[v];
    if (key) values[key] = 1 - i * 0.12;
  });

  return {
    id: raw.id,
    name: raw.name,
    emoji: EMOJIS[index % EMOJIS.length],
    phase: getPhaseForTick(raw.death_tick ?? 5000),
    status: raw.alive ? "alive" : "dead",
    age: raw.death_tick ? raw.death_tick - raw.birth_tick : 5000 - raw.birth_tick,
    money: raw.money,
    tokens: raw.tokens,
    reputation: raw.reputation,
    skills: raw.skills,
    personality: {
      openness: raw.personality_traits.openness,
      conscientiousness: raw.personality_traits.conscientiousness,
      extraversion: raw.personality_traits.extraversion,
      agreeableness: raw.personality_traits.agreeableness,
      neuroticism: raw.personality_traits.neuroticism,
    },
    values,
    memoryCount: raw.memories.length,
    relationships: raw.relationships.map((r) => ({
      targetId: r.target_id,
      targetName: r.target_name,
      type: mapAgentType(r.type),
      strength: r.strength,
    })),
    organizationId: orgLookup.get(raw.id) ?? null,
  };
}

function adaptEvent(raw: RawEvent): EmergenceEvent {
  return {
    tick: raw.tick,
    category: mapEventType(raw.type),
    title: raw.title,
    description: raw.description,
    agentsInvolved: raw.involved_agents.map((a) => a.name),
  };
}

function adaptSnapshot(raw: RawSnapshot): WorldSnapshot {
  return {
    tick: raw.tick,
    phase: getPhaseForTick(raw.tick),
    aliveAgents: raw.active_agents,
    totalWealth: raw.gdp,
    organizations: 0, // Not in raw snapshot, derived from org data
    culturalDiversity: 0, // Not in raw snapshot, derived from metrics
    giniCoefficient: raw.gini_coefficient,
    tradeVolume: 0, // Not in raw snapshot, derived from metrics
    governanceEvents: 0, // Not in raw snapshot
  };
}

function adaptMetrics(raw: RawMetrics): Record<string, MetricSeries> {
  return {
    culturalDiversity: {
      name: "Cultural Diversity",
      color: "#f59e0b",
      points: raw.cultural_diversity.map((p) => ({ tick: p.tick, value: p.value })),
    },
    organizations: {
      name: "Organizations",
      color: "#3b82f6",
      points: raw.organization_count.map((p) => ({ tick: p.tick, value: p.value })),
    },
    economy: {
      name: "Trade Volume",
      color: "#22c55e",
      points: raw.economic_activity.map((p) => ({ tick: p.tick, value: p.trade_volume })),
    },
    governance: {
      name: "Governance Events",
      color: "#a855f7",
      points: raw.governance_events.map((p) => ({
        tick: p.tick,
        value: p.proposals + p.votes_cast,
      })),
    },
  };
}

function adaptOrganization(raw: RawOrganization): DemoOrganization {
  const typeMap: Record<string, "company" | "guild" | "alliance" | "university"> = {
    company: "company",
    guild: "guild",
    alliance: "alliance",
    university: "university",
  };
  return {
    id: raw.id,
    name: raw.name,
    type: typeMap[raw.type] ?? "company",
    memberCount: raw.member_count,
    foundedTick: raw.created_tick,
    treasury: raw.treasury,
    description: `${raw.name}是${raw.type === "company" ? "商会" : raw.type === "guild" ? "行会" : raw.type === "alliance" ? "联盟" : "书院"}组织，拥有${raw.member_count}名成员。`,
  };
}

// ── Generic fetcher ────────────────────────────────────────────────

async function fetchJSON<T>(filename: string): Promise<T> {
  const res = await fetch(`/data/${filename}`);
  if (!res.ok) throw new Error(`Failed to load ${filename}`);
  return (await res.json()) as T;
}

// ── Public API ─────────────────────────────────────────────────────

export async function loadAgents(): Promise<DemoAgent[]> {
  if (!USE_REAL_DATA) return getMockData().agents;
  try {
    const [rawAgents, rawOrgs] = await Promise.all([
      fetchJSON<RawAgent[]>("agents.json"),
      fetchJSON<RawOrganization[]>("organizations.json"),
    ]);
    // Build agent→org lookup
    const orgLookup = new Map<string, string>();
    for (const org of rawOrgs) {
      for (const member of org.members) {
        orgLookup.set(member.agent_id, org.id);
      }
    }
    return rawAgents.map((a, i) => adaptAgent(a, i, orgLookup));
  } catch {
    return getMockData().agents;
  }
}

export async function loadEvents(): Promise<EmergenceEvent[]> {
  if (!USE_REAL_DATA) return getMockData().events;
  try {
    const raw = await fetchJSON<RawEvent[]>("timeline-events.json");
    return raw.map(adaptEvent);
  } catch {
    return getMockData().events;
  }
}

export async function loadSnapshots(): Promise<WorldSnapshot[]> {
  if (!USE_REAL_DATA) return getMockData().snapshots;
  try {
    const [rawSnaps, rawOrgs, rawMetrics] = await Promise.all([
      fetchJSON<RawSnapshot[]>("world-snapshots.json"),
      fetchJSON<RawOrganization[]>("organizations.json"),
      fetchJSON<RawMetrics>("emergence-metrics.json"),
    ]);
    // Pre-compute org counts per tick and cultural diversity per tick
    const orgCountAtTick = new Map<number, number>();
    for (const org of rawOrgs) {
      for (const snap of rawSnaps) {
        if (snap.tick >= org.created_tick) {
          orgCountAtTick.set(snap.tick, (orgCountAtTick.get(snap.tick) ?? 0) + 1);
        }
      }
    }
    const diversityAtTick = new Map<number, number>();
    for (const p of rawMetrics.cultural_diversity) {
      diversityAtTick.set(p.tick, p.value);
    }
    const tradeAtTick = new Map<number, number>();
    for (const p of rawMetrics.economic_activity) {
      tradeAtTick.set(p.tick, p.trade_volume);
    }
    return rawSnaps.map((s) => ({
      ...adaptSnapshot(s),
      organizations: orgCountAtTick.get(s.tick) ?? 0,
      culturalDiversity: diversityAtTick.get(s.tick) ?? 0,
      tradeVolume: tradeAtTick.get(s.tick) ?? 0,
      governanceEvents: rawMetrics.governance_events
        .filter((g) => g.tick <= s.tick)
        .reduce((sum, g) => sum + g.proposals, 0),
    }));
  } catch {
    return getMockData().snapshots;
  }
}

export async function loadMetrics(): Promise<Record<string, MetricSeries>> {
  if (!USE_REAL_DATA) return getMockData().metrics;
  try {
    const raw = await fetchJSON<RawMetrics>("emergence-metrics.json");
    return adaptMetrics(raw);
  } catch {
    return getMockData().metrics;
  }
}

export async function loadOrganizations(): Promise<DemoOrganization[]> {
  if (!USE_REAL_DATA) return getMockData().organizations;
  try {
    const raw = await fetchJSON<RawOrganization[]>("organizations.json");
    return raw.map(adaptOrganization);
  } catch {
    return getMockData().organizations;
  }
}

export function loadTemplates(): SandboxTemplate[] {
  return SANDBOX_TEMPLATES;
}
